"""Full service catalog — 91 services from the original TZ Status React UI."""

SEED_SERVICES = [
    # Government (28)
    {"name": "NIDA", "category": "government", "url": "https://www.nida.go.tz"},
    {"name": "TRA", "category": "government", "url": "https://www.tra.go.tz"},
    {"name": "BRELA", "category": "government", "url": "https://www.brela.go.tz"},
    {"name": "HESLB", "category": "government", "url": "https://www.heslb.go.tz"},
    {"name": "Ajira Portal", "category": "government", "url": "https://ajira.go.tz"},
    {"name": "eGA Portal", "category": "government", "url": "https://www.ega.go.tz"},
    {"name": "NSSF", "category": "government", "url": "https://www.nssf.go.tz"},
    {"name": "NHIF", "category": "government", "url": "https://www.nhif.or.tz"},
    {"name": "Immigration eServices", "category": "government", "url": "https://eservices.immigration.go.tz"},
    {"name": "eCitizen Tanzania", "category": "government", "url": "https://eservices.gov.go.tz"},
    {"name": "Judiciary Portal", "category": "government", "url": "https://www.judiciary.go.tz"},
    {"name": "GePG", "category": "government", "url": "https://www.gepg.go.tz"},
    {"name": "TANePS", "category": "government", "url": "https://www.taneps.go.tz"},
    {"name": "TCRA", "category": "government", "url": "https://www.tcra.go.tz"},
    {"name": "OSHA", "category": "government", "url": "https://www.osha.go.tz"},
    {"name": "LATRA", "category": "government", "url": "https://www.latra.go.tz"},
    {"name": "TBS", "category": "government", "url": "https://www.tbs.go.tz"},
    {"name": "TMDA", "category": "government", "url": "https://www.tmda.go.tz"},
    {"name": "WCF", "category": "government", "url": "https://www.wcf.go.tz"},
    {"name": "RITA", "category": "government", "url": "https://www.rita.go.tz"},
    {"name": "NECTA", "category": "government", "url": "https://www.necta.go.tz"},
    {"name": "NACTVET", "category": "government", "url": "https://www.nactvet.go.tz"},
    {"name": "TCU", "category": "government", "url": "https://www.tcu.go.tz"},
    {"name": "TIC", "category": "government", "url": "https://www.tic.go.tz"},
    {"name": "TANESCO", "category": "government", "url": "https://www.tanesco.co.tz"},
    {"name": "EWURA", "category": "government", "url": "https://www.ewura.go.tz"},
    {"name": "Ministry of Education Portal", "category": "government", "url": "https://www.moe.go.tz"},
    {"name": "Ministry of Health Systems", "category": "government", "url": "https://www.moh.go.tz"},
    # Banks (17)
    {"name": "CRDB", "category": "bank", "url": "https://crdbbank.co.tz"},
    {"name": "NMB", "category": "bank", "url": "https://www.nmbbank.co.tz"},
    {"name": "NBC", "category": "bank", "url": "https://www.nbc.co.tz"},
    {"name": "Stanbic", "category": "bank", "url": "https://www.stanbicbank.co.tz"},
    {"name": "DTB", "category": "bank", "url": "https://www.dtbtanzania.com"},
    {"name": "Exim", "category": "bank", "url": "https://www.eximbank-tz.com"},
    {"name": "Equity", "category": "bank", "url": "https://equitygroupholdings.com/tz"},
    {"name": "Absa", "category": "bank", "url": "https://www.absa.co.tz"},
    {"name": "KCB", "category": "bank", "url": "https://ke.kcbgroup.com/tz"},
    {"name": "Access Bank", "category": "bank", "url": "https://www.accessbankplc.com/tz"},
    {"name": "Akiba Commercial Bank", "category": "bank", "url": "https://www.akibabank.com"},
    {"name": "UBA", "category": "bank", "url": "https://www.ubagroup.com/tanzania"},
    {"name": "Ecobank", "category": "bank", "url": "https://www.ecobank.com/tz"},
    {"name": "Standard Chartered", "category": "bank", "url": "https://www.sc.com/tz"},
    {"name": "BOA", "category": "bank", "url": "https://www.boabank.co.tz"},
    {"name": "Mkombozi Bank", "category": "bank", "url": "https://www.mkombozibank.co.tz"},
    {"name": "Amana Bank", "category": "bank", "url": "https://www.amanabank.co.tz"},
    # Telecom (6)
    {"name": "Vodacom", "category": "telecom", "url": "https://www.vodacom.co.tz"},
    {"name": "Airtel", "category": "telecom", "url": "https://www.airtel.co.tz"},
    {"name": "Yas (Tigo)", "category": "telecom", "url": "https://www.yas.co.tz"},
    {"name": "Halotel", "category": "telecom", "url": "https://www.halotel.co.tz"},
    {"name": "TTCL", "category": "telecom", "url": "https://www.ttcl.co.tz"},
    {"name": "Zantel", "category": "telecom", "url": "https://www.zantel.co.tz"},
    # Mobile money (8)
    {"name": "M-Pesa", "category": "mobile_money", "url": "https://www.vodacom.co.tz/m-pesa"},
    {"name": "Airtel Money", "category": "mobile_money", "url": "https://www.airtel.co.tz/airtel-money"},
    {"name": "Mixx", "category": "mobile_money", "url": "https://www.yas.co.tz/mixx-by-yas"},
    {"name": "Halopesa", "category": "mobile_money", "url": "https://www.halotel.co.tz/halopesa"},
    {"name": "T-Pesa", "category": "mobile_money", "url": "https://www.ttcl.co.tz"},
    {"name": "Selcom", "category": "mobile_money", "url": "https://selcommobile.com"},
    {"name": "NALA", "category": "mobile_money", "url": "https://www.nala.money"},
    {"name": "Azam Pesa", "category": "mobile_money", "url": "https://www.azampesa.co.tz"},
    # Airlines (4)
    {"name": "Air Tanzania", "category": "airlines", "url": "https://www.airtanzania.co.tz"},
    {"name": "Precision Air", "category": "airlines", "url": "https://www.precisionairtz.com"},
    {"name": "Flightlink", "category": "airlines", "url": "https://www.flightlink.co.tz"},
    {"name": "Auric Air", "category": "airlines", "url": "https://www.auricair.com"},
    # Transport (7)
    {"name": "TRC", "category": "transport", "url": "https://www.trc.co.tz"},
    {"name": "SGR Ticketing", "category": "transport", "url": "https://www.trc.co.tz/sgr"},
    {"name": "TAZARA", "category": "transport", "url": "https://www.tazara.co.tz"},
    {"name": "Bolt", "category": "transport", "url": "https://bolt.eu/en-tz"},
    {"name": "Uber", "category": "transport", "url": "https://www.uber.com/tz/en"},
    {"name": "Yango", "category": "transport", "url": "https://yango.com/tz"},
    {"name": "Little Ride", "category": "transport", "url": "https://www.little.bz"},
    # E-commerce (4)
    {"name": "Jumia", "category": "ecommerce", "url": "https://www.jumia.co.tz"},
    {"name": "Kilimall", "category": "ecommerce", "url": "https://www.kilimall.co.tz"},
    {"name": "Zoom Tanzania", "category": "ecommerce", "url": "https://zoomtanzania.com"},
    {"name": "Kupatana", "category": "ecommerce", "url": "https://www.kupatana.com"},
    # Media (7)
    {"name": "Azam TV", "category": "media", "url": "https://www.azamtv.co.tz"},
    {"name": "DSTV Tanzania", "category": "media", "url": "https://www.dstv.com/tz"},
    {"name": "Wasafi FM", "category": "media", "url": "https://www.wasafi.media"},
    {"name": "Clouds FM", "category": "media", "url": "https://www.cloudsfm.com"},
    {"name": "ITV", "category": "media", "url": "https://www.itv.co.tz"},
    {"name": "TBC", "category": "media", "url": "https://www.tbc.go.tz"},
    {"name": "Mwananchi", "category": "media", "url": "https://www.mwananchi.co.tz"},
    # Universities (10)
    {"name": "UDSM", "category": "universities", "url": "https://www.udsm.ac.tz"},
    {"name": "ARU", "category": "universities", "url": "https://www.aru.ac.tz"},
    {"name": "OUT", "category": "universities", "url": "https://www.out.ac.tz"},
    {"name": "ATC", "category": "universities", "url": "https://www.atc.ac.tz"},
    {"name": "SUA", "category": "universities", "url": "https://www.sua.ac.tz"},
    {"name": "MUHAS", "category": "universities", "url": "https://www.muhas.ac.tz"},
    {"name": "IFM", "category": "universities", "url": "https://www.ifm.ac.tz"},
    {"name": "CBE", "category": "universities", "url": "https://www.cbe.ac.tz"},
    {"name": "Mzumbe", "category": "universities", "url": "https://www.mzumbe.ac.tz"},
    {"name": "UDOM", "category": "universities", "url": "https://www.udom.ac.tz"},
]
